# Generated by Django 5.1.3 on 2024-12-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='photo',
        ),
    ]
